#!/usr/bin/env bash
set -euo pipefail

TARGET="${1:-$(pwd)}"
ROOT="/Users/lol/Docs/instructions.ai"
TARGET="$(cd "$TARGET" && pwd)"

mkdir -p "$TARGET/ai-system" "$TARGET/.cursor/rules" "$TARGET/.windsurf/rules" "$TARGET/.antigravity/rules" "$TARGET/.github" "$TARGET/.junie"

copy_if_missing() {
  local src="$1"
  local dest="$2"
  if [ ! -e "$dest" ]; then
    cp "$src" "$dest"
    echo "created $dest"
  else
    echo "kept existing $dest"
  fi
}

detect_file() {
  local path="$1"
  if [ -e "$TARGET/$path" ]; then
    printf '%s' "$path"
  fi
}

list_existing() {
  local label="$1"
  shift
  local found=()
  local item
  for item in "$@"; do
    if [ -e "$TARGET/$item" ]; then
      found+=("`$item`")
    fi
  done
  if [ "${#found[@]}" -gt 0 ]; then
    local joined
    joined=$(IFS=', '; echo "${found[*]}")
    echo "- $label: $joined"
  else
    echo "- $label: Not detected"
  fi
}

detect_package_scripts() {
  if [ ! -f "$TARGET/package.json" ]; then
    return
  fi

  if command -v node >/dev/null 2>&1; then
    node - "$TARGET/package.json" <<'NODE'
const fs = require("fs");
const path = process.argv[2];
const pkg = JSON.parse(fs.readFileSync(path, "utf8"));
const scripts = pkg.scripts || {};
const keys = ["install", "dev", "start", "test", "lint", "typecheck", "build", "preview", "deploy"];
for (const key of keys) {
  if (key === "install") continue;
  if (scripts[key]) console.log(`- ${key}: npm run ${key}`);
}
if (pkg.packageManager) console.log(`- package manager: ${pkg.packageManager}`);
NODE
  else
    echo "- package scripts: package.json detected, but node was unavailable for parsing"
  fi
}

detect_package_dependencies() {
  if [ ! -f "$TARGET/package.json" ]; then
    return
  fi

  if command -v node >/dev/null 2>&1; then
    node - "$TARGET/package.json" <<'NODE'
const fs = require("fs");
const pkg = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const deps = {...(pkg.dependencies || {}), ...(pkg.devDependencies || {})};
const has = (...names) => names.some((name) => deps[name]);
const lines = [];
if (has("next")) lines.push("- Frontend framework: Next.js");
else if (has("vite")) lines.push("- Frontend build tool: Vite");
else if (has("react")) lines.push("- Frontend framework: React");
else if (has("vue")) lines.push("- Frontend framework: Vue");
else if (has("svelte", "@sveltejs/kit")) lines.push("- Frontend framework: Svelte/SvelteKit");
else if (has("astro")) lines.push("- Frontend framework: Astro");
if (has("express")) lines.push("- Backend framework: Express");
if (has("fastify")) lines.push("- Backend framework: Fastify");
if (has("@nestjs/core")) lines.push("- Backend framework: NestJS");
if (has("typescript")) lines.push("- Language: TypeScript");
if (has("tailwindcss")) lines.push("- Styling: Tailwind CSS");
if (has("@mui/material")) lines.push("- UI library: MUI");
if (has("antd")) lines.push("- UI library: Ant Design");
if (has("shadcn", "lucide-react", "class-variance-authority")) lines.push("- UI patterns: shadcn/lucide-style React components likely");
if (has("prisma")) lines.push("- Database ORM: Prisma");
if (has("drizzle-orm")) lines.push("- Database ORM: Drizzle");
if (has("@supabase/supabase-js")) lines.push("- Backend service: Supabase");
if (has("firebase")) lines.push("- Backend service: Firebase");
if (has("vitest")) lines.push("- Test framework: Vitest");
if (has("jest")) lines.push("- Test framework: Jest");
if (has("@playwright/test")) lines.push("- E2E testing: Playwright");
if (has("cypress")) lines.push("- E2E testing: Cypress");
if (lines.length) console.log(lines.join("\n"));
NODE
  fi
}

detect_python_project() {
  if [ -f "$TARGET/pyproject.toml" ] || [ -f "$TARGET/requirements.txt" ] || [ -f "$TARGET/Pipfile" ]; then
    echo "- Language/runtime: Python"
  fi
  if find "$TARGET" -maxdepth 3 -type f \( -name 'main.py' -o -name 'app.py' \) -print -quit | grep -q .; then
    if rg -q "FastAPI|from fastapi|import fastapi" "$TARGET" -g '*.py' 2>/dev/null; then
      echo "- Backend framework: FastAPI"
    elif rg -q "Flask|from flask|import flask" "$TARGET" -g '*.py' 2>/dev/null; then
      echo "- Backend framework: Flask"
    elif rg -q "streamlit" "$TARGET" -g '*.py' 2>/dev/null; then
      echo "- App framework: Streamlit"
    fi
  fi
}

generate_project_context() {
  local output="$1"
  local project_name
  project_name="$(basename "$TARGET")"
  local now
  now="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  {
    echo "# Project Context"
    echo
    echo "Generated by \`instructions.ai\` bootstrap on $now."
    echo
    echo "## Goal"
    echo
    if [ -f "$TARGET/README.md" ]; then
      echo "- Project name: $project_name"
      echo "- README detected. Agents must read \`README.md\` for the human-written project goal before implementation."
      local first_heading
      first_heading="$(rg -m 1 '^# ' "$TARGET/README.md" 2>/dev/null | sed 's/^# //')"
      if [ -n "$first_heading" ]; then
        echo "- README title: $first_heading"
      fi
    else
      echo "- Project name: $project_name"
      echo "- Human goal: Fill this in with the product/business objective."
    fi
    echo
    echo "## Auto-Detected Stack"
    echo
    detect_package_dependencies || true
    detect_python_project || true
    list_existing "Java/Gradle" "build.gradle" "build.gradle.kts" "settings.gradle" "pom.xml"
    list_existing "Mobile/native" "app.json" "eas.json" "android" "ios"
    list_existing "Database/schema" "prisma/schema.prisma" "drizzle.config.ts" "supabase" "sql" "db"
    list_existing "Deployment" "vercel.json" "netlify.toml" "render.yaml" "wrangler.toml" "Dockerfile" "docker-compose.yml"
    list_existing "Environment examples" ".env.example" ".env.local.example" ".env.production.example"
    echo
    echo "## Local Commands"
    echo
    if [ -f "$TARGET/package.json" ]; then
      if [ -f "$TARGET/pnpm-lock.yaml" ]; then
        echo "- install: pnpm install"
      elif [ -f "$TARGET/yarn.lock" ]; then
        echo "- install: yarn install"
      elif [ -f "$TARGET/bun.lockb" ] || [ -f "$TARGET/bun.lock" ]; then
        echo "- install: bun install"
      else
        echo "- install: npm install"
      fi
      detect_package_scripts || true
    fi
    if [ -f "$TARGET/requirements.txt" ]; then
      echo "- python install: python -m pip install -r requirements.txt"
    fi
    if [ -f "$TARGET/pyproject.toml" ]; then
      echo "- python project: inspect pyproject.toml for tool-specific commands"
    fi
    if [ -f "$TARGET/Makefile" ]; then
      echo "- make commands: inspect \`Makefile\`"
    fi
    echo
    echo "## Architecture Notes"
    echo
    echo "- Agents must inspect the actual folder structure before changing files."
    echo "- Reuse existing components, utilities, services, routes, schemas, tests, and naming conventions."
    echo "- Do not rewrite architecture unless explicitly requested."
    echo
    echo "## Users And Use Cases"
    echo
    echo "- Primary users: Fill in if not obvious from README/product docs."
    echo "- Key workflows: Agents should infer from routes, screens, tests, README, and existing docs, then confirm when uncertain."
    echo "- Success criteria: Define per task before implementation."
    echo
    echo "## Design System"
    echo
    list_existing "Style/config files" "tailwind.config.js" "tailwind.config.ts" "components.json" "src/index.css" "app/globals.css" "styles/globals.css"
    echo "- Agents must preserve local typography, spacing, color, component, and motion patterns."
    echo
    echo "## Important Constraints"
    echo
    echo "- Do not expose secrets from .env files."
    echo "- Do not modify unrelated files."
    echo "- Do not add speculative features."
    echo "- Verify with the strongest available checks before final response."
    echo
    echo "## Known Issues"
    echo
    echo "- Fill in known bugs, deployment constraints, failing tests, API limits, or pending migrations."
    echo
    echo "## Required Agent Behavior"
    echo
    echo "- Read \`AGENTS.md\`, this file, and \`HANDOFF.md\` before implementation."
    echo "- Update \`HANDOFF.md\` after meaningful work."
    echo "- If this generated context conflicts with source files, trust source files and update this context."
  } > "$output"
}

install_project_context() {
  local generated="$TARGET/PROJECT_CONTEXT.generated.md"
  generate_project_context "$generated"

  if [ ! -e "$TARGET/PROJECT_CONTEXT.md" ]; then
    cp "$generated" "$TARGET/PROJECT_CONTEXT.md"
    echo "created $TARGET/PROJECT_CONTEXT.md from auto-detected project data"
  elif rg -q "Describe what this project is trying to accomplish|Generated by \`instructions.ai\` bootstrap" "$TARGET/PROJECT_CONTEXT.md" 2>/dev/null; then
    cp "$generated" "$TARGET/PROJECT_CONTEXT.md"
    echo "refreshed $TARGET/PROJECT_CONTEXT.md from auto-detected project data"
  else
    echo "kept existing customized $TARGET/PROJECT_CONTEXT.md"
    echo "created/updated $generated with auto-detected project data"
  fi

  if [ ! -e "$TARGET/ai-system/project_context.md" ] || rg -q "Describe what this project is trying to accomplish|Generated by \`instructions.ai\` bootstrap" "$TARGET/ai-system/project_context.md" 2>/dev/null; then
    cp "$TARGET/PROJECT_CONTEXT.md" "$TARGET/ai-system/project_context.md"
    echo "synced $TARGET/ai-system/project_context.md"
  fi
}

copy_if_missing "$ROOT/templates/AGENTS.md" "$TARGET/AGENTS.md"
copy_if_missing "$ROOT/templates/CLAUDE.md" "$TARGET/CLAUDE.md"
copy_if_missing "$ROOT/templates/GEMINI.md" "$TARGET/GEMINI.md"
copy_if_missing "$ROOT/templates/.cursorrules" "$TARGET/.cursorrules"
copy_if_missing "$ROOT/templates/copilot-instructions.md" "$TARGET/.github/copilot-instructions.md"
copy_if_missing "$ROOT/templates/junie-guidelines.md" "$TARGET/.junie/guidelines.md"
copy_if_missing "$ROOT/templates/HANDOFF.md" "$TARGET/HANDOFF.md"

copy_if_missing "$ROOT/ide-rules/cursor-instructions-ai.mdc" "$TARGET/.cursor/rules/instructions-ai.mdc"
copy_if_missing "$ROOT/ide-rules/windsurf-instructions-ai.md" "$TARGET/.windsurf/rules/instructions-ai.md"
copy_if_missing "$ROOT/ide-rules/antigravity-instructions-ai.md" "$TARGET/.antigravity/rules/instructions-ai.md"

copy_if_missing "$ROOT/templates/HANDOFF.md" "$TARGET/ai-system/handoff.md"
install_project_context

echo "Project prepared for Codex, Claude, Cursor, Gemini-style agents, Windsurf, Antigravity, and generic IDE assistants."
