"""Roadmap Export Generator for Markdown, JSON, and Printable HTML/PDF."""

import json
from typing import Dict, Any, Set

def build_markdown_export(roadmap: Dict[str, Any], completed_nodes: Set[str], progress_pct: int) -> str:
    """Generates a complete, beautiful Markdown export document."""
    all_nodes = [n for p in roadmap.get("phases", []) for n in p.get("nodes", [])]
    done = len(completed_nodes)

    lines = [
        f"# 🎓 Personalized Learning Path: {roadmap.get('role', 'Curriculum')}",
        "",
        f"**Goal:** {roadmap.get('goal', 'Custom Goal')}  ",
        f"**Curriculum Mastery:** {progress_pct}% ({done} of {len(all_nodes)} milestones completed)  ",
        f"**Generated by:** SkillPath AI (Team Cortex — PathFinder Prototype)  ",
        "",
        "---",
        "",
        "## 🗺️ Roadmap Architecture",
        ""
    ]

    for phase in roadmap.get("phases", []):
        lines.extend([
            f"### {phase.get('phase', 'Phase')}",
            "",
            "| ID | Milestone Module | Type | Provider | Duration | Prerequisites | Status |",
            "|:---|:-----------------|:-----|:---------|:---------|:--------------|:-------|"
        ])
        for n in phase.get("nodes", []):
            is_done = n["id"] in completed_nodes
            status = "✅ Completed" if is_done else "⬜ Pending"
            prereqs_str = ", ".join(n.get("prereqs", [])) if n.get("prereqs") else "None"
            title = str(n.get("title", "")).replace("|", "\\|")
            provider = str(n.get("provider", "")).replace("|", "\\|")
            lines.append(
                f"| `{n['id']}` | **{title}** | {n.get('type', 'Course')} | {provider} | "
                f"{n.get('duration', '2 weeks')} | {prereqs_str} | {status} |"
            )
        lines.append("")

    lines.extend([
        "---",
        "",
        "## 💡 Explainable AI (XAI) Rationales",
        ""
    ])
    for phase in roadmap.get("phases", []):
        for n in phase.get("nodes", []):
            skills = ", ".join(n.get("skills", ["General"]))
            lines.append(f"#### `{n['id']}`: {n.get('title')}")
            lines.append(f"- **Why Recommended:** {n.get('why', 'Core required competency.')}")
            lines.append(f"- **Target Skills:** `{skills}`")
            lines.append("")

    lines.extend([
        "---",
        "",
        "## ✅ Actionable Milestone Checklist",
        ""
    ])
    for phase in roadmap.get("phases", []):
        lines.append(f"**{phase.get('phase', '')}**")
        for n in phase.get("nodes", []):
            mark = "x" if n["id"] in completed_nodes else " "
            lines.append(f"- [{mark}] **{n['id']}**: {n.get('title')} ({n.get('duration', '2w')})")
        lines.append("")

    return "\n".join(lines) + "\n"


def build_printable_html_export(roadmap: Dict[str, Any], completed_nodes: Set[str], progress_pct: int) -> str:
    """Generates a standalone, beautifully styled HTML document ready for PDF printing."""
    all_nodes = [n for p in roadmap.get("phases", []) for n in p.get("nodes", [])]
    done = len(completed_nodes)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Path — {roadmap.get('role', 'PathFinder')}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@600;700&display=swap');
        body {{
            font-family: 'Inter', sans-serif;
            margin: 40px;
            color: #18181b;
            background: #ffffff;
            line-height: 1.6;
        }}
        h1, h2, h3 {{
            font-family: 'Space Grotesk', sans-serif;
            color: #09090b;
        }}
        .header-box {{
            border-bottom: 2px solid #e4e4e7;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .progress-bar-bg {{
            background: #e4e4e7;
            border-radius: 8px;
            height: 14px;
            width: 100%;
            margin: 15px 0;
            overflow: hidden;
        }}
        .progress-bar-fill {{
            background: #2563eb;
            height: 100%;
            width: {progress_pct}%;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0 30px 0;
        }}
        th, td {{
            padding: 10px 14px;
            border: 1px solid #e4e4e7;
            text-align: left;
            font-size: 13px;
        }}
        th {{
            background: #f4f4f5;
            font-weight: 600;
        }}
        .badge {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: 600;
            background: #eff6ff;
            color: #1d4ed8;
        }}
        .status-done {{
            color: #059669;
            font-weight: 600;
        }}
        .status-pending {{
            color: #71717a;
        }}
        @media print {{
            body {{ margin: 20px; }}
            .no-print {{ display: none; }}
        }}
    </style>
</head>
<body>
    <div class="header-box">
        <h1>🎓 Personalized Learning Path: {roadmap.get('role', 'Curriculum')}</h1>
        <p><strong>Goal:</strong> {roadmap.get('goal', '')}<br>
        <strong>Curriculum Mastery:</strong> {progress_pct}% ({done} of {len(all_nodes)} milestones completed)<br>
        <strong>Engine:</strong> SkillPath AI (Team Cortex — PathFinder Prototype)</p>
        
        <div class="progress-bar-bg">
            <div class="progress-bar-fill"></div>
        </div>
    </div>

    <h2>Roadmap Milestones</h2>
"""

    for phase in roadmap.get("phases", []):
        html += f"""
        <h3>{phase.get('phase', 'Phase')}</h3>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Module Title</th>
                    <th>Type</th>
                    <th>Provider</th>
                    <th>Duration</th>
                    <th>Prerequisites</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
        """
        for n in phase.get("nodes", []):
            is_done = n["id"] in completed_nodes
            status_class = "status-done" if is_done else "status-pending"
            status_text = "✓ Completed" if is_done else "Pending"
            prereqs_str = ", ".join(n.get("prereqs", [])) if n.get("prereqs") else "None"
            html += f"""
                <tr>
                    <td><code>{n['id']}</code></td>
                    <td><strong>{n.get('title', '')}</strong><br><small style="color:#71717a;">{n.get('why', '')}</small></td>
                    <td><span class="badge">{n.get('type', 'Course')}</span></td>
                    <td>{n.get('provider', 'Online')}</td>
                    <td>{n.get('duration', '2w')}</td>
                    <td>{prereqs_str}</td>
                    <td class="{status_class}">{status_text}</td>
                </tr>
            """
        html += """
            </tbody>
        </table>
        """

    html += """
</body>
</html>
"""
    return html
